file:
  in_dir: './data'
  model_dir: './model'
  out_dir: './out'
  num_stage: 18
  h: 320
  w: 320

train:
  gpu: 0
  lr: 1.0e-3
  epoch: 4000
  save_epoch: 500
  num_sample_ray: 2
  lr_decay_epoch: 500
  lr_decay_rate: 0.5
  batch_size: 40

encoding:
  otype: 'Grid'
  type: 'Hash'
  n_levels: 16
  n_features_per_level: 8
  log2_hashmap_size: 18
  base_resolution: 2
  per_level_scale: 2
  interpolation: 'Linear'

mlp:
  otype: 'FullyFusedMLP'
  activation: 'ReLU'
  output_activation: 'None'
  n_neurons: 64
  n_hidden_layers: 2